package br.com.fiap.techchallenge.G13.TechChallenge2.G13.core.domain.model;

import br.com.fiap.techchallenge.G13.TechChallenge2.G13.core.domain.enums.UserType;

public abstract class User {

    protected String id;
    protected String name;
    protected UserType userType;
    protected String email;
    protected String login;
    protected String password;

    // Note: 'id' is intentionally not included in this constructor.
    // It will be generated by the persistence layer (MongoDB)
    // and can be added later if needed.
    public User(String name, UserType type, String email, String login, String password) {
        this.name = name;
        this.userType = type;
        this.email = email;
        this.login = login;
        this.password = password;
    }


    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public UserType getUserType() {
        return userType;
    }

    public String getEmail() {
        return email;
    }

    public String getLogin() {
        return login;
    }

    public String getPassword() {
        return password;
    }

    public void updateName(String name) {
        this.name = name;
    }

    public void updateEmail(String email) {
        this.email = email;
    }

    public void updateLogin(String login) {
        this.login = login;
    }

    public void updatePassword(String password) {
        this.password = password;
    }

}
